### ISSUE TITLE
Error on viewing sub flowsheet

### ISSUE THREAD

**Issue by bh206** [DanWBR/dwsim6#152]
Hi,

In DWSim 6.4.9 the error below happens when a sub flowsheet is attempted to be viewed. Running on Win 10 with 64 bit package. Any advice appreciated, thank you.

System.MissingMemberException: Public member 'Flowsheet' on type 'GraphicsSurface' not found.
   at Microsoft.VisualBasic.CompilerServices.Symbols.Container.GetMembers(String& MemberName, Boolean ReportErrors)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.LateSet(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean OptimisticSet, Boolean RValueBase, CallType CallType)
   at DWSIM.UnitOperations.EditingForm_Flowsheet_Viewer.FlowsheetUOViewerForm_Load(Object sender, EventArgs e) in C:\Users\Daniel\source\repos\DanWBR\dwsim6\DWSIM.UnitOperations\Editing Forms\Supporting\EditingForm_Flowsheet_Viewer.vb:line 10
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.SetVisible() in C:\Users\Daniel\source\repos\DanWBR\dwsim6\DWSIM.Controls.DockPanel\WinFormsUI\Docking\DockContentHandler.cs:line 780
   at WeifenLuo.WinFormsUI.Docking.DockPane.set_ActiveContent(IDockContent value) in C:\Users\Daniel\source\repos\DanWBR\dwsim6\DWSIM.Controls.DockPanel\WinFormsUI\Docking\DockPane.cs:line 198
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Activate() in C:\Users\Daniel\source\repos\DanWBR\dwsim6\DWSIM.Controls.DockPanel\WinFormsUI\Docking\DockContentHandler.cs:line 692
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Show(DockPanel dockPanel, DockState dockState) in C:\Users\Daniel\source\repos\DanWBR\dwsim6\DWSIM.Controls.DockPanel\WinFormsUI\Docking\DockContentHandler.cs:line 884
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Show(DockPanel dockPanel) in C:\Users\Daniel\source\repos\DanWBR\dwsim6\DWSIM.Controls.DockPanel\WinFormsUI\Docking\DockContentHandler.cs:line 839
   at WeifenLuo.WinFormsUI.Docking.DockContent.Show(DockPanel dockPanel) in C:\Users\Daniel\source\repos\DanWBR\dwsim6\DWSIM.Controls.DockPanel\WinFormsUI\Docking\DockContent.cs:line 239
   at DWSIM.FlowsheetSurfaceControl.FlowsheetSurfaceControl_MouseDoubleClick(Object sender, MouseEventArgs e) in C:\Users\Daniel\source\repos\DanWBR\dwsim6\DWSIM\Forms\Flowsheet Components\FlowsheetSurface_SkiaSharp\FlowsheetSurfaceControl.vb:line 111
   at System.Windows.Forms.Control.OnMouseDoubleClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by bh206** [comment]
Very many thanks indeed, much appreciated.
