### ISSUE TITLE
[Bug] Bug in Component Viewer

### ISSUE THREAD

**Issue by Greg66** [DanWBR/dwsim6#230]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
As soon as i want to inspect a pure component with Pure Component Viewer an error is issued. See 

**To Reproduce**
1. Open Component viewer for any component
2. you can go on and inspect the component

**Expected behavior**
No error

**Bug report**
System.NullReferenceException: Object reference not set to an instance of an object.
   at DWSIM.SharedClasses.SystemsOfUnits.Converter.ConvertFromSI(String units, Double value) in \\agserv4\userhomes\G90020\Data\GitHub\dwsim6\DWSIM.SharedClasses\UnitsOfMeasure\SystemsOfUnits.vb:line 1666
   at DWSIM.FormPureComp.Populate() in \\agserv4\userhomes\G90020\Data\GitHub\dwsim6\DWSIM\Utilities\Pure Compound Properties\FormPureComp.vb:line 764
   at DWSIM.FormPureComp.FormPureComp_Shown(Object sender, EventArgs e) in \\agserv4\userhomes\G90020\Data\GitHub\dwsim6\DWSIM\Utilities\Pure Compound Properties\FormPureComp.vb:line 1054
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS]
 - Version [e.g. v6.4.1]

**Additional context**

**Comment by Greg66** [comment]
Further investigation of the problem showed that for property "GasOilRatio" -> ".gor" no unit was definied in SystemOfUnits.vb except for "English" unit system.
see:  SystemOfUnits.vb Line 995
