### ISSUE TITLE
[Bug]  Modified UNIFAC (NIST) error

### ISSUE THREAD

**Issue by vitcbra** [DanWBR/dwsim6#243]
System.Collections.Generic.KeyNotFoundException: A chave fornecida não estava presente no dicionário.
   em Microsoft.VisualBasic.CompilerServices.Symbols.Container.InvokeMethod(Method TargetProcedure, Object[] Arguments, Boolean[] CopyBack, BindingFlags Flags)
   em Microsoft.VisualBasic.CompilerServices.NewLateBinding.CallMethod(Container BaseReference, String MethodName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack, BindingFlags InvocationFlags, Boolean ReportErrors, ResolutionFailure& Failure)
   em Microsoft.VisualBasic.CompilerServices.NewLateBinding.InternalLateIndexGet(Object Instance, Object[] Arguments, String[] ArgumentNames, Boolean ReportErrors, ResolutionFailure& Failure, Boolean[] CopyBack)
   em Microsoft.VisualBasic.CompilerServices.NewLateBinding.ObjectLateGet(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack)
   em Microsoft.VisualBasic.CompilerServices.NewLateBinding.LateGet(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack)
   em DWSIM.Thermodynamics.FormConfigPropertyPackage.FillUNIFACParamTable(String type) na C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.Thermodynamics\EditingForms\PropertyPackages\FormConfigPropertyPackage.vb:linha 63
   em DWSIM.Thermodynamics.FormConfigPropertyPackage.FormConfigPR_Load(Object sender, EventArgs e) na C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.Thermodynamics\EditingForms\PropertyPackages\FormConfigPropertyPackage.vb:linha 393
   em System.EventHandler.Invoke(Object sender, EventArgs e)
   em System.Windows.Forms.Form.OnLoad(EventArgs e)
   em System.Windows.Forms.Form.OnCreateControl()
   em System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   em System.Windows.Forms.Control.CreateControl()
   em System.Windows.Forms.Control.WmShowWindow(Message& m)
   em System.Windows.Forms.Control.WndProc(Message& m)
   em System.Windows.Forms.Form.WmShowWindow(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

![Captura de Tela (148)](https://user-images.githubusercontent.com/80062371/144123612-43262fea-7800-487a-93bc-869f9afcf2a5.png)

**Comment by DanWBR** [comment]
@vitcbra can you attach the simulation file?

**Comment by vitcbra** [comment]
@DanWBR The error is present since the Property Package is add. I using 7.0.1 version and windows 10.
![Captura de Tela (149)](https://user-images.githubusercontent.com/80062371/144264290-99242b2b-fe79-4a6d-8373-c5bcef99a508.png)
"System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at Microsoft.VisualBasic.CompilerServices.Symbols.Container.InvokeMethod(Method TargetProcedure, Object[] Arguments, Boolean[] CopyBack, BindingFlags Flags)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.CallMethod(Container BaseReference, String MethodName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack, BindingFlags InvocationFlags, Boolean ReportErrors, ResolutionFailure& Failure)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.InternalLateIndexGet(Object Instance, Object[] Arguments, String[] ArgumentNames, Boolean ReportErrors, ResolutionFailure& Failure, Boolean[] CopyBack)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.ObjectLateGet(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.LateGet(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack)
   at DWSIM.Thermodynamics.FormConfigPropertyPackage.FillUNIFACParamTable(String type) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.Thermodynamics\EditingForms\PropertyPackages\FormConfigPropertyPackage.vb:line 63
   at DWSIM.Thermodynamics.FormConfigPropertyPackage.FormConfigPR_Load(Object sender, EventArgs e) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.Thermodynamics\EditingForms\PropertyPackages\FormConfigPropertyPackage.vb:line 393
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)"

**Comment by DanWBR** [comment]
@vitcbra it works correctly here when adding to a new flowsheet too. I need your file, if possible.
