### ISSUE TITLE
[Bug] Error loading Compound Creator study

### ISSUE THREAD

**Issue by Greg66** [DanWBR/dwsim6#319]
**Describe the bug**
Loading a Compound Creator Study (.dwcsd2) will issue an error.

**To Reproduce**
1. Create a new study and save it
2. Load Study

**Expected behavior**
No Error

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windwos
 - Version 7.5.5

**Additional context - Error message**
Newtonsoft.Json.JsonSerializationException: Unexpected end when deserializing object. Path 'RegressRoS', line 301, position 0.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ThrowUnexpectedEndException(JsonReader reader, JsonContract contract, Object currentObject, String message)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at DWSIM.FormMain.LoadFile(IVirtualFile handler) in \\agserv4\userhomes\G90020\Data\GitHub\dwsim6\DWSIM\Forms\MainWindow\FormMain.vb:line 3559
   at DWSIM.FormMain.LoadFileDialog(Boolean dashboardpicker) in \\agserv4\userhomes\G90020\Data\GitHub\dwsim6\DWSIM\Forms\MainWindow\FormMain.vb:line 3501
   at DWSIM.FormMain.OpenToolStripButton_Click(Object sender, EventArgs e) in \\agserv4\userhomes\G90020\Data\GitHub\dwsim6\DWSIM\Forms\MainWindow\FormMain.vb:line 3710
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by DanWBR** [comment]
@Greg66 your file might be corrupted, can you open it with a text editor and check? I've fixed the corruption source, anyway.

**Comment by Greg66** [comment]
Thanks! Great, that works now :-)
As you noted, the file was corrupted.

Gregor
