### ISSUE TITLE
[Bug] When trying to include other flowsheet as user model

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#330]
**Describe the bug**
When trying to include a completed flowsheet (Cavetts problem from samples, but occurs for any model)model as a user model in dwsim an unhandled exception occurs when trying to view the flowsheet. 

The following exception occurs: 

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at DWSIM.UnitOperations.EditingForm_Flowsheet_Viewer.FlowsheetUOViewerForm_Load(Object sender, EventArgs e) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.UnitOperations\EditingForms\Supporting\EditingForm_Flowsheet_Viewer.vb:line 9
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Form.SetVisibleCore(Boolean value)
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.SetVisible() in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.Controls.DockPanel\WinFormsUI\Docking\DockContentHandler.cs:line 780
   at WeifenLuo.WinFormsUI.Docking.DockPane.set_ActiveContent(IDockContent value) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.Controls.DockPanel\WinFormsUI\Docking\DockPane.cs:line 198
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Activate() in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.Controls.DockPanel\WinFormsUI\Docking\DockContentHandler.cs:line 692
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Show(DockPanel dockPanel, DockState dockState) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.Controls.DockPanel\WinFormsUI\Docking\DockContentHandler.cs:line 884
   at WeifenLuo.WinFormsUI.Docking.DockContentHandler.Show(DockPanel dockPanel) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.Controls.DockPanel\WinFormsUI\Docking\DockContentHandler.cs:line 839
   at WeifenLuo.WinFormsUI.Docking.DockContent.Show(DockPanel dockPanel) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.Controls.DockPanel\WinFormsUI\Docking\DockContent.cs:line 239
   at DWSIM.FormFlowsheet.DisplayForm(Object form) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\Forms\Flowsheet\FormFlowsheet.vb:line 3032
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/58475535/171208463-a463cd58-e37e-41e2-a881-d5489e9b17ed.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, 
 - Version [e.g. v7.5

**Comment by DanWBR** [comment]
@andr1976 did you initialize the flowsheet in the control panel before trying to view it? Initialization actually loads the flowsheet from the file

**Comment by andr1976** [comment]
No, I didn't :-) it is not 100% intuitive. I initialised, but still getting an occasional unhandled exception. I will try harder.

**Comment by andr1976** [comment]
Made Cavetts problem work by using the same components in the master sheet as in the loaded file (subflowsheet), and carefully connected inlet/outlet ports and mapped the inlets and outlets before trying to view it. 
Ok, so part of the problem with Cavetts problem might be the components not being easily mapped from say CO2 (DWSIM) to DioxidoDeCarbano (no CAS no).

**Comment by DanWBR** [comment]
@andr1976 you're absolutely right, it is not intuitive at all. Also, Cavett's problem flowsheet was created with compounds from the original database, where the names were still in portuguese. DWSIM automatically maps compounds when they have the same name.
