### ISSUE TITLE
[Bug] Unhandled exception starting v8.0.2

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#336]
System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: Culture is not supported.
Parameter name: culture
3072 (0x0c00) is an invalid culture identifier. ---> System.Globalization.CultureNotFoundException: Culture is not supported.
Parameter name: culture
3072 (0x0c00) is an invalid culture identifier.
   at System.Globalization.CultureInfo.InitializeFromCultureId(Int32 culture, Boolean useUserOverride)
   at FileHelpers.ConvertHelpers.CreateCulture(String decimalSepOrCultureName)
   at FileHelpers.ConvertHelpers.GetDefaultConverter(String fieldName, Type fieldType, String defaultCultureName)
   at FileHelpers.FieldBase..ctor(FieldInfo fi, String defaultCultureName)
   at FileHelpers.FieldBase.CreateField(FieldInfo fi, TypedRecordAttribute recordAttribute)
   at FileHelpers.RecordInfo.CreateCoreFields(IList`1 fields, TypedRecordAttribute recordAttribute)
   at FileHelpers.RecordInfo.InitRecordFields()
   at FileHelpers.RecordInfo..ctor(Type recordType)
   at FileHelpers.RecordInfo.RecordInfoFactory.Resolve(Type type)
   at FileHelpers.EngineBase..ctor(Type recordType, Encoding encoding)
   at FileHelpers.FileHelperEngine`1..ctor(Encoding encoding)
   at DWSIM.Thermodynamics.PropertyPackages.Auxiliary.PengRobinson..ctor() in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.Thermodynamics\PropertyPackages\Models\PengRobinson.vb:line 85
   at DWSIM.Thermodynamics.PropertyPackages.PengRobinsonPropertyPackage..ctor() in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.Thermodynamics\PropertyPackages\PengRobinson.vb:line 39
   at DWSIM.FormMain.AddPropPacks() in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\Forms\MainWindow\FormMain.vb:line 745
   at DWSIM.FormMain..ctor() in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\Forms\MainWindow\FormMain.Designer.vb:line 830
   --- End of inner exception stack trace ---
   at DWSIM.My.MyProject.MyForms.Create__Instance__[T](T Instance) in :line 192
   at DWSIM.My.MyApplication.OnCreateMainForm() in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\My Project\Application.Designer.vb:line 33
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()

**Comment by andr1976** [comment]
Hmm, seems my IT department messed around with my regional settings and that somehow caused it

**Comment by hdavid16** [comment]
I'm not seeing this issue when starting up on v8.0.2 (Windows desktop version)
