### ISSUE TITLE
[Bug] Insert master property table error on v8.0.2

### ISSUE THREAD

**Issue by hdavid16** [DanWBR/dwsim6#337]
I get this error when trying to add a master property table:
```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at DWSIM.FormConfigureMasterTable.FormConfigureMasterTable_Load(Object sender, EventArgs e) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\Forms\FormConfigureMasterTable.vb:line 33
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
I am able to add property tables successfully, just not the master one...

**Comment by DanWBR** [comment]
@hdavid16 How do I reproduce this? can you attach the file?
