### ISSUE TITLE
Error when reopening regression study [Bug] 

### ISSUE THREAD

**Issue by ErichMace** [DanWBR/dwsim6#393]
IMPORTANT: This section is for code-related bugs. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
When re-opening a regression study, the following error is consistently generated.

**To Reproduce**
1. Generate regression study
2. Close study
3. Re-open study

**Expected behavior**
Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path 'results', line 195, position 2783.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at DWSIM.FormMain.LoadFile(IVirtualFile handler) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\Forms\MainWindow\FormMain.vb:line 3647
   at DWSIM.FormMain.LoadFileDialog(Boolean dashboardpicker) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\Forms\MainWindow\FormMain.vb:line 3559
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 8.3.2

**Additional context**

![DWSIM_Error_RegressionStudy](https://user-images.githubusercontent.com/119608456/205085212-a5a808a6-cccb-477a-953d-dd6ee8826554.JPG)

**Comment by hdavid16** [comment]
@ErichMace please add a title to the issue to make it easier to manage.

**Comment by DanWBR** [comment]
@ErichMace I couldn't reproduce this issue in v8.3.4, please upload a test case file if possible.
