### ISSUE TITLE
[Bug] 'Object reference not set to an instance of an object' - Dynamic Simulation

### ISSUE THREAD

**Issue by rcroy** [DanWBR/dwsim6#424]
**Describe the bug**
When opening a dynamic simulation like Water Tank Level Control, the following error occurs:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at DWSIM.UnitOperations.UnitOperations.UnitOpBaseClass.GetPropertyValue(String prop, IUnitsOfMeasure su) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.UnitOperations\BaseClasses\UnitOperations.vb:line 146
   at DWSIM.UnitOperations.UnitOperations.Tank.GetPropertyValue(String prop, IUnitsOfMeasure su) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.UnitOperations\UnitOperations\Tank.vb:line 348
   at DWSIM.FormDynamicsManager.UpdateIndicatorList() in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\Forms\FlowsheetComponents\FormDynamicsManager.vb:line 162
   at DWSIM.FormDynamicsManager.FormDynamicsManager_Load(Object sender, EventArgs e) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\Forms\FlowsheetComponents\FormDynamicsManager.vb:line 37
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**To Reproduce**
1. Open the DWSIM Classic UI
2. From Samples, select 'Dynamic Simulation - Water Tank Level Control'
3. See error

The same error also occurs when trying to run the dynamic simulation.

**Expected behavior**
Should load without error, and run dynamic simulation without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/60727578/216277624-05844e07-915d-4f5e-841f-cf98440984d1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 8.3.5

**Additional context**
This doesn't happen in 8.3.4.

**Comment by DanWBR** [comment]
@rcroy please redownload the installer and try again.
