### ISSUE TITLE
[Bug]  Problem with Absorber/Extraction column

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#433]
**Describe the bug**
When creating a simple absorber/extraction column with a CO2 stream (bottom) and water (top stream) using Raoults law, when solving the column the entire flowsheet gets a big red cross and the followingexception occurs 
 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at DWSIM.UnitOperations.UnitOperations.AbsorptionColumn.GetPropertyValue(String prop, IUnitsOfMeasure su) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.UnitOperations\UnitOperations\RigorousColumn.vb:line 1507
   at DWSIM.Drawing.SkiaSharp.GraphicObjects.Tables.FloatingTableGraphic.Draw(Object g) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.Drawing.SkiaSharp\GraphicObjects\Table\FloatingTable.vb:line 286
   at DWSIM.Drawing.SkiaSharp.GraphicsSurface.UpdateCanvas(SKCanvas DrawingCanvas) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.Drawing.SkiaSharp\GraphicsSurface\DesignSurface.vb:line 477
   at DWSIM.FlowsheetSurfaceControl.OnPaintSurface(SKPaintSurfaceEventArgs e) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\Forms\FlowsheetComponents\FlowsheetSurfaceSkiaSharp\FlowsheetSurfaceControl.vb:line 36
   at SkiaSharp.Views.Desktop.SKControl.OnPaint(PaintEventArgs e) in C:\Users\Daniel\ source\repos\DanWBR\dwsim\DWSIM.SkiaSharp.Views.Desktop\SKControl.cs:line 57
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPt

**To Reproduce**

**Expected behavior**
Solved column - no unhandled exception, no red cross 

**Screenshots**
![image](https://user-images.githubusercontent.com/58475535/220205071-8759b84b-e10f-4d51-94ef-abb0d03eab88.png)

**Desktop (please complete the following information):**
 - OS:  Windows,
 - Version [e.g. v8.3.5]

**Additional context**
See atcched file 
[test_absorber.zip](https://github.com/DanWBR/dwsim/files/10788042/test_absorber.zip)

**Comment by DanWBR** [comment]
yes, it was indeed fixed in https://github.com/DanWBR/dwsim/commit/7d69c5d6df2df83b776076a0a34cb5a5d08ef5e9#diff-a28e930d897c497f1dccb1b1ec8ad52fd7a9b0a96ae4abd2f2f098ab34bda904
