### ISSUE TITLE
DWSIM Integration [Bug] 

### ISSUE THREAD

**Issue by ALE-Peax** [DanWBR/dwsim6#440]
Dear Opem Team,

I’m trying to use your solution for a DWSIM simulation of a PEM.
I have downloaded the .exe file on my machine but I don’t succeed to integrated within DWSIM.
I always face the issue:

System.Exception: 163: Please install DWSIM Python Environments Add-On and try again. ---> System.Exception: Please install DWSIM Python Environments Add-On and try again.
   at DWSIM.UnitOperations.UnitOperations.PEMFC_Amphlett.Calculate(Object args) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.UnitOperations\UnitOperations\CleanEnergies\PEMFC_Amphlett.vb:line 104
   at DWSIM.SharedClasses.UnitOperations.BaseClass.Solve() in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.SharedClasses\BaseClass\SimulationObjectBaseClasses.vb:line 442
   at DWSIM.FlowsheetSolver.FlowsheetSolver.CalculateObjectAsync(Object fobj, CalculationArgs objArgs, CancellationToken ct) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.FlowsheetSolver\FlowsheetSolver.vb:line 225
   at DWSIM.FlowsheetSolver.FlowsheetSolver.ProcessQueueInternalAsync(Object fobj, CancellationToken ct) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM.FlowsheetSolver\FlowsheetSolver.vb:line 522
   --- End of inner exception stack trace ---

Could you please help me?  

Best regards,
Antoine

**Comment by DanWBR** [comment]
@ALE-Peax the OPEM team is another project. DWSIM uses OPEM to calculate the PEM.

Also, this is not a bug. You must extract the exe file as per instructions on the download page.

<img width="294" alt="Captura de Tela 2023-03-01 às 09 28 09" src="https://user-images.githubusercontent.com/2669419/222152467-1783da45-07c6-4315-bf67-7f6c20a0eaac.png">
