### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by tusharekhande** [DanWBR/dwsim6#448]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Concurrent.ConcurrentDictionary`2.get_Item(TKey key)
   at AutomaticTranslation.AutomaticTranslator.<>c.<SetMainWindow>b__27_1(String text) in C:\Users\Daniel\source\repos\DanWBR\AutomaticTranslationPlugin\Handler.cs:line 357
   at DWSIM.DWSIM.App.GetLocalString(String id, String locale) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\Objects\Classes\Shared\SharedFunctions.vb:line 206
   at DWSIM.FormFlowsheet..ctor() in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\Forms\Flowsheet\FormFlowsheet.vb:line 169
   at DWSIM.FormMain.NewToolStripButton_Click(Object sender, EventArgs e) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\Forms\MainWindow\FormMain.vb:line 4235
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by DanWBR** [comment]
@tusharekhande please update DWSIM to v8.4.2.
