### ISSUE TITLE
DTL via python throws exception from Ipopt.Finalize()

### ISSUE THREAD

**Issue by andr1976** [DanWBR/dwsim6#47]
When DTL is run via python and the script terminates an unhandled exception occurs. Happens both when running
python script.py
and
pythin -i script.py 
For the latter exception occurs when interactive pythin is exited with Ctrl-Z

Unhandled Exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at Cureos.Numerics.Ipopt.FreeIpoptProblem(IntPtr ipopt_problem)
   at Cureos.Numerics.Ipopt.Dispose(Boolean disposing)
   at Cureos.Numerics.Ipopt.Finalize()

**Expected behavior**
No exception. 

**Desktop (please complete the following information):**
 - Win 10 x64
 - DTL_v6.3.7615

**Pythin code to reproduce**

```
import clr, array

from System import String, Double, Array, Reflection, Exception

dtlpath = "C:\\Users\ANRA\OneDrive - Ramboll\\Documents\\DWSIM Application Data\\PythonDTL\\"

clr.AddReference(dtlpath + "DWSIM.Thermodynamics.StandaloneLibrary.dll")

from DWSIM.Thermodynamics import Streams, PropertyPackages, CalculatorInterface
from DWSIM.Interfaces.Enums import FlashCalculationType
from DWSIM.Thermodynamics.PropertyPackages.Auxiliary.FlashAlgorithms import *

import CapeOpen

dtlc = CalculatorInterface.Calculator()

print(String.Format("DTL version: {0}", Reflection.Assembly.GetAssembly(dtlc.GetType()).GetName().Version))
print()

dtlc.Initialize()

#nrtl = PropertyPackages.NRTLPropertyPackage(True)
pr = PropertyPackages.PengRobinsonPropertyPackage(True)

dtlc.TransferCompounds(pr)

T = 94+273.15 #K
P = 25*101325.0 #Pa
  
carray = Array[String](["Water", "Methane", "Propane", "Isobutane", "N-butane", "N-decane"])
comparray = Array[Double]([0.1, 0.3, 0.1, 0.1, 0.1, 0.3])

#result2 = dtlc.PTFlash(pr,3,P,T,carray,comparray)


ms = dtlc.CreateMaterialStream(carray, comparray)

print ("Calculating Material Stream Phase Equilibria and Properties at T = " + str(T) + " K and P = " + str(P) + " Pa")
#print ("Mass Flow = 1000 kg/s")

ms.SetPropertyPackage(pr)
ms.SetPressure(P)
ms.SetTemperature(T)
ms.SetMolarFlow(1.0) # kg/s
#nlvlle=NestedLoopsImmiscible
#nlvlle.StabSearchCompIDs = String(r"Water")
#nlvlle.StabSearchSeverity = 0
#ms.FlashAlgorithm = nlvlle

ms.SetFlashSpec("PT")
ms.Calculate()

vapordensity = ms.GetPhase("Vapor").Properties.density
print("Vapor Phase Density: " + str(vapordensity) + " kg/m3")
print("Vapour molecular weight: " + str(ms.GetPhase("Vapour").Properties.molecularWeight)+ " kg/kmole")

liquiddensity = ms.GetPhase("Liquid1").Properties.density
print("Liquid1 Phase Density: " + str(liquiddensity) + " kg/m3")
print("Liquid1 molecular weight: " + str(ms.GetPhase("liquid1").Properties.molecularWeight) + " kg/kmole")

liquid2density = ms.GetPhase("Liquid2").Properties.density
print("Liquid 2 Phase Density: " + str(liquid2density) + " kg/m3")
print("Liquid2 molecular weight: " + str(ms.GetPhase("Liquid2").Properties.molecularWeight) + " kg/kmole")

for comp in ms.GetPhase("Overall").Compounds.Values:
    print(comp.ConstantProperties.Name + " Overall Molar Flow: " + str(comp.MolarFlow) + " mol/s")

vaporflow = ms.GetPhase("Vapor").Properties.massflow
print("Vapor Phase Mass Flow: " + str(vaporflow) + " kg/s")

liquidflow = ms.GetPhase("Liquid1").Properties.massflow
print("Liquid Phase Mass Flow: " + str(liquidflow) + " kg/s")

```

**Comment by DanWBR** [comment]
Fixed in DTL v6.3.7617. You must copy the two IPOPT files to Windows\System32, at least for now. The definitive fix for DWSIM will be in v6.3 Update 4. https://github.com/DanWBR/dwsim6/commit/44dbfdacfedbaa0a64eb89e2d758ee16995be6df and https://github.com/DanWBR/dwsim6/commit/e3598d1e79b99b52661853c3574448b51176e5d4

**Comment by andr1976** [comment]
Yes, it seems to work

**Comment by DanWBR** [comment]
DTL v6.3.7619 preloads IPOPT libraries from the directory where DTL DLL is located. No need to copy them to System32 anymore. https://github.com/DanWBR/dwsim6/commit/11459b8c3e57d2c211d3cf823a367505091818e8
