### ISSUE TITLE
[Bug] This property must be set before runtime is initialized at DWSIM.GlobalSettings.Settings.

### ISSUE THREAD

**Issue by log12311** [DanWBR/dwsim6#509]
**Describe the bug**
This error was raised during the calculation of a Unit Operation or Material Stream.

System.InvalidOperationException: This property must be set before runtime is initialized
   at DWSIM.GlobalSettings.Settings.InitializePythonEnvironment(String pythonpath) in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM.GlobalSettings\Settings.vb:line 209
   at DWSIM.Thermodynamics.ReaktoroPropertyPackage.ReaktoroFlash.Flash_PT(Array Vx, Double T, Double P) in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM.Thermodynamics.ReaktoroPropertyPackage\ReaktoroFlash.vb:line 122
   at DWSIM.Thermodynamics.ReaktoroPropertyPackage.ReaktoroPropertyPackage.DW_CalcEquilibrium(FlashSpec spec1, FlashSpec spec2) in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM.Thermodynamics.ReaktoroPropertyPackage\ReaktoroPP.vb:line 145
   at DWSIM.Thermodynamics.Streams.MaterialStream.Calculate(Boolean equilibrium, Boolean properties) in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM.Thermodynamics\MaterialStream\MaterialStream.vb:line 610
   at DWSIM.Thermodynamics.Streams.MaterialStream.Calculate(Object args) in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM.Thermodynamics\MaterialStream\MaterialStream.vb:line 453
   at DWSIM.SharedClasses.UnitOperations.BaseClass.Solve() in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM.SharedClasses\BaseClass\SimulationObjectBaseClasses.vb:line 465
   at DWSIM.FlowsheetSolver.FlowsheetSolver.CalculateMaterialStreamAsync(Object fobj, ISimulationObject ms, CancellationToken ct) in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM.FlowsheetSolver\FlowsheetSolver.vb:line 389
   at DWSIM.FlowsheetSolver.FlowsheetSolver.ProcessQueueInternalAsync(Object fobj, CancellationToken ct) in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM.FlowsheetSolver\FlowsheetSolver.vb:line 592

The Reaktoro(Aqueous electrolytes)  solve method is used.

 - Version [windows v11]

**Comment by DanWBR** [comment]
@log12311 you need to define the path to a python 3.7-3.9 installation in Edit > Global Settings.

**Comment by log12311** [comment]
well，the problem is caused by a different version of the python installation
