### ISSUE TITLE
[BUG]  source code string cannot contain null bytes

### ISSUE THREAD

**Issue by log12311** [DanWBR/dwsim6#510]
**Describe the bug**

This error was raised during the calculation of a Unit Operation or Material Stream.

Python.Runtime.PythonException: ValueError: source code string cannot contain null bytes
   at DWSIM.Thermodynamics.ReaktoroPropertyPackage.ReaktoroFlash.Flash_PT(Array Vx, Double T, Double P) in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM.Thermodynamics.ReaktoroPropertyPackage\ReaktoroFlash.vb:line 296
   at DWSIM.Thermodynamics.ReaktoroPropertyPackage.ReaktoroPropertyPackage.DW_CalcEquilibrium(FlashSpec spec1, FlashSpec spec2) in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM.Thermodynamics.ReaktoroPropertyPackage\ReaktoroPP.vb:line 145
   at DWSIM.Thermodynamics.Streams.MaterialStream.Calculate(Boolean equilibrium, Boolean properties) in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM.Thermodynamics\MaterialStream\MaterialStream.vb:line 610
   at DWSIM.Thermodynamics.Streams.MaterialStream.Calculate(Object args) in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM.Thermodynamics\MaterialStream\MaterialStream.vb:line 453
   at DWSIM.SharedClasses.UnitOperations.BaseClass.Solve() in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM.SharedClasses\BaseClass\SimulationObjectBaseClasses.vb:line 465
   at DWSIM.FlowsheetSolver.FlowsheetSolver.CalculateMaterialStreamAsync(Object fobj, ISimulationObject ms, CancellationToken ct) in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM.FlowsheetSolver\FlowsheetSolver.vb:line 389
   at DWSIM.FlowsheetSolver.FlowsheetSolver.ProcessQueueInternalAsync(Object fobj, CancellationToken ct) in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM.FlowsheetSolver\FlowsheetSolver.vb:line 592

SOLVE METHOD  Reaktoro (Aqueous Electrolytes) 
*python Version 3.9

**Comment by DanWBR** [comment]
@log12311 flowsheet?

**Comment by log12311** [comment]
as follows：
![1689821047264](https://github.com/DanWBR/dwsim/assets/139832145/294c1a26-ae87-4237-923c-0fdc145707e6)

![1689820974096](https://github.com/DanWBR/dwsim/assets/139832145/250da456-3da8-4a3d-b6a0-cf9109096ecd)

**Comment by DanWBR** [comment]
@log12311 I mean the simulation file

**Comment by log12311** [comment]
[1.zip](https://github.com/DanWBR/dwsim/files/12135375/1.zip)

**Comment by DanWBR** [comment]
@log12311 I ran your flowsheet successfully. I recommend trying a Python 3.9 distribution from winpython.org

**Comment by log12311** [comment]
👌thanks
