### ISSUE TITLE
[Bug] Changing Hydraulic Profile Type

### ISSUE THREAD

**Issue by FMusik** [DanWBR/dwsim6#512]
Hi,

I've been trying to change the pipe type from straight to a Tee and i'm getting the following error:

System.NullReferenceException: Object reference not set to an instance of an object.
   at DWSIM.UnitOperations.PipeHydraulicProfileEditor.Button4_Click(Object sender, EventArgs e) in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM.UnitOperations\EditingForms\Supporting\EditingForm_Pipe_HydraulicProfileEditor.vb:line 1226
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by DanWBR** [comment]
@FMusik are you running v8.5.0?

**Comment by FMusik** [comment]
I am, yes.

**Comment by DanWBR** [comment]
@FMusik can you share your flowsheet? save it right after doing this action, zip it and drag it here, please.

**Comment by FMusik** [comment]
After I saved and closed it, I also got the following error:

System.NullReferenceException: Object reference not set to an instance of an object.
   at DWSIM.FormFlowsheet.FormChild2_FormClosed(Object sender, FormClosedEventArgs e) in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM\Forms\Flowsheet\FormFlowsheet.vb:line 826
   at System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

See attached file.
[DWSIM.zip](https://github.com/DanWBR/dwsim/files/12110758/DWSIM.zip)

**Comment by DanWBR** [comment]
@FMusik are you entering the internal diameter for the Tee?

**Comment by FMusik** [comment]
@DanWBR no, none of the pipe segments have been sized.  I was creating the workflow prior to inputting all the dimensions.

**Comment by DanWBR** [comment]
you need to inform all the required data for the section before adding it to the profile.

**Comment by FMusik** [comment]
@DanWBR good to know.  I appreciate the help, thanks!

**Comment by DanWBR** [comment]
@FMusik in the next version you'll be able to add the whole profile from a table, see #500
