### ISSUE TITLE
Material Streams not updating - Classic UI - v8.6.7

### ISSUE THREAD

**Issue by dk009dk** [DanWBR/dwsim6#566]
**Material Streams Issue - Classis UI v8.6.7**

Classic UI
Material Streams are not updating in latest update v8.6.7
When I click on **Refresh** button, only one stream is displaying in spreadsheet of material streams.
Issue arises only after updating to v8.6.7

**Error**
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at unvell.ReoGrid.Worksheet.GetGridBounds(Int32 row, Int32 col)
   at unvell.ReoGrid.Worksheet.CreateCell(Int32 row, Int32 col, Boolean updateStyle)
   at DWSIM.MaterialStreamPanel.UpdateTable() in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\Forms\FlowsheetComponents\MaterialStreamPanel.vb:line 117
   at DWSIM.MaterialStreamPanel.ToolStripButton1_Click(Object sender, EventArgs e) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\Forms\FlowsheetComponents\MaterialStreamPanel.vb:line 152
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**To Reproduce**
[Dynamic Simulation - Water Tank Level Control.zip](https://github.com/DanWBR/dwsim/files/13884441/Dynamic.Simulation.-.Water.Tank.Level.Control.zip)

**Screenshots**
![image](https://github.com/DanWBR/dwsim/assets/60841968/01b17f7e-5538-4d74-bd52-5e47a2cb7acb)

 - OS: Windows
 - Version 8.6.7

**Comment by DanWBR** [comment]
@dk009dk please re-download the installer and try again.
