### ISSUE TITLE
[Bug] Error CompCreator3

### ISSUE THREAD

**Issue by derbuur** [DanWBR/dwsim6#621]
IMPORTANT: This section is meant for bug reporting only. For usage issues, please go to the [Support Forums](https://sourceforge.net/p/dwsim/discussion/).

**Describe the bug**
Conversion from string "- 6.640301E-10" to type 'Double' is not valid.

System.InvalidCastException: Conversion from string "- 6.640301E-10" to type 'Double' is not valid. ---> System.FormatException: Input string was not in a correct format.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(String Value, NumberFormatInfo NumberFormat)
   --- End of inner exception stack trace ---
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(String Value, NumberFormatInfo NumberFormat)
   at DWSIM.FormCompoundCreator.btnViewCPLiquid_Click(Object sender, EventArgs e) in C:\Users\Daniel\source\repos\DanWBR\dwsim\DWSIM\Forms\CompoundCreator\FormCompoundCreator.vb:line 2939
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**To Reproduce**

PLEASE ATTACH THE ZIPPED FLOWSHEET FILE and/or inform the steps to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Linux, macOS]
 - Version [e.g. v6.4.1]

**Additional context**

Conversion from string "- 6.640301E-10" to type 'Double' is not valid.

**Comment by DanWBR** [comment]
@derbuur you have a space after the minus sign
