### ISSUE TITLE
[Bug] Unhandled Error: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by SaraDC87** [DanWBR/dwsim6#685]
I recently downloaded the latest version of DWSIM (v8.8.2) and ever since, even though I'm running my simulations without problem (Flowsheet was calculated correctly), there's an "unhandled error" when I save and close the models: 

Exception message: Object reference not set to an instance of an object.
Call stack: System.NullReferenceException: Object reference not set to an instance of an object.
   at DWSIM.FormFlowsheet.ReleaseResources() in C:\Users\danie\source\repos\DanWBR\dwsim\DWSIM\Forms\Flowsheet\FormFlowsheet.vb:line 743
   at System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Also, sometimes the properties of one material stream "jump" to another without any apparent reason, giving me wrong results. This is rare, but it has happened a few times, and I don't know if it could be related to the same error.

Here is a ZIPPED FLOWSHEET FILE of one of the cases where this happened, but it is actually appearing with every case I run:

[026_M20_75-0.zip](https://github.com/user-attachments/files/17475635/026_M20_75-0.zip)

I'm not sure if it is due to the new version or if I have a "hidden" mistake in my model. 

**Desktop:**
 - OS: Windows 10
 - Version 22H2

Thanks for your help!

**Comment by DanWBR** [comment]
thanks for reporting!

**Comment by SaraDC87** [comment]
I updated to v8.8.3 and the same error is still happening.
